# Generated by Django 5.0.4 on 2024-05-04 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=3000)),
            ],
        ),
        migrations.AlterField(
            model_name='phrase',
            name='embedding',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='phrase',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.topic'),
        ),
        migrations.CreateModel(
            name='UnknownQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.phrase')),
                ('user_select_answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.topic')),
            ],
        ),
    ]
