# Generated by Django 5.0.4 on 2024-05-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_topic_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
