# Generated by Django 5.0.4 on 2024-05-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_topic_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unknownquestion',
            old_name='user_select_answer',
            new_name='user_select_topic',
        ),
        migrations.AddField(
            model_name='unknownquestion',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
