# Generated by Django 5.0.4 on 2024-05-09 11:32

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_user_select_answer_unknownquestion_user_select_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unknownquestion',
            name='question',
            field=models.TextField(verbose_name=app.models.Phrase),
        ),
    ]
