# Generated by Django 5.0.4 on 2024-05-09 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_unknownquestion_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unknownquestion',
            old_name='user_select_topic',
            new_name='select_topic',
        ),
    ]
