# Generated by Django 5.0.4 on 2024-05-09 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_unknownquestion_select_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unknownquestion',
            name='select_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.topic'),
        ),
    ]
